package com.ssinfo.ws.rider.mapping;

// Generated 4 Oct, 2014 9:40:17 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CoriderInfoTbl generated by hbm2java
 */
@Entity
@Table(name = "corider_info_tbl", schema = "public")
public class CoriderInfoTbl implements java.io.Serializable {

	private long coriderId;
	private SearchInfoTbl searchInfoTbl;
	private UserTbl userTbl;
	private String status;

	public CoriderInfoTbl() {
	}

	public CoriderInfoTbl(long coriderId) {
		this.coriderId = coriderId;
	}

	public CoriderInfoTbl(long coriderId, SearchInfoTbl searchInfoTbl,
			UserTbl userTbl, String status) {
		this.coriderId = coriderId;
		this.searchInfoTbl = searchInfoTbl;
		this.userTbl = userTbl;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="corider_sequence")
	@SequenceGenerator(
		name="corider_sequence",sequenceName="corider_sequence",	allocationSize=1)
	@Column(name = "corider_id", unique = true, nullable = false)
	public long getCoriderId() {
		return this.coriderId;
	}

	public void setCoriderId(long coriderId) {
		this.coriderId = coriderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "search_id")
	public SearchInfoTbl getSearchInfoTbl() {
		return this.searchInfoTbl;
	}

	public void setSearchInfoTbl(SearchInfoTbl searchInfoTbl) {
		this.searchInfoTbl = searchInfoTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public UserTbl getUserTbl() {
		return this.userTbl;
	}

	public void setUserTbl(UserTbl userTbl) {
		this.userTbl = userTbl;
	}

	@Column(name = "status", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
