package com.ssinfo.ws.rider.mapping;

// Generated 4 Oct, 2014 9:40:17 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DeviceInfoTbl generated by hbm2java
 */
@Entity
@Table(name = "device_info_tbl", schema = "public")
public class DeviceInfoTbl implements java.io.Serializable {
	
	private long deviceInfoId;
	private UserTbl userTbl;
	private String deviceOsType;
	private String deviceOsVersion;
	private String appVersion;
	private String deviceModelNo;
	private Double deviceScreenSize;
	private String deviceScreenResolution;

	public DeviceInfoTbl() {
	}

	public DeviceInfoTbl(long deviceInfoId) {
		this.deviceInfoId = deviceInfoId;
	}

	public DeviceInfoTbl(long deviceInfoId, UserTbl userTbl,
			String deviceOsType, String deviceOsVersion, String appVersion,
			String deviceModelNo, Double deviceScreenSize,
			String deviceScreenResolution) {
		this.deviceInfoId = deviceInfoId;
		this.userTbl = userTbl;
		this.deviceOsType = deviceOsType;
		this.deviceOsVersion = deviceOsVersion;
		this.appVersion = appVersion;
		this.deviceModelNo = deviceModelNo;
		this.deviceScreenSize = deviceScreenSize;
		this.deviceScreenResolution = deviceScreenResolution;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="device_sequence")
	@SequenceGenerator(
		name="device_sequence",
		sequenceName="device_sequence",
		allocationSize=1
	)
	@Column(name = "device_info_id", unique = true, nullable = false)
	public long getDeviceInfoId() {
		return this.deviceInfoId;
	}

	public void setDeviceInfoId(long deviceInfoId) {
		this.deviceInfoId = deviceInfoId;
	}

	
	@ManyToOne(fetch = FetchType.EAGER,cascade=CascadeType.ALL)
	@JoinColumn(name = "user_id")
	public UserTbl getUserTbl() {
		return this.userTbl;
	}

	public void setUserTbl(UserTbl userTbl) {
		this.userTbl = userTbl;
	}

	@Column(name = "device_os_type", length = 100)
	public String getDeviceOsType() {
		return this.deviceOsType;
	}

	public void setDeviceOsType(String deviceOsType) {
		this.deviceOsType = deviceOsType;
	}

	@Column(name = "device_os_version", length = 20)
	public String getDeviceOsVersion() {
		return this.deviceOsVersion;
	}

	public void setDeviceOsVersion(String deviceOsVersion) {
		this.deviceOsVersion = deviceOsVersion;
	}

	@Column(name = "app_version", length = 10)
	public String getAppVersion() {
		return this.appVersion;
	}

	public void setAppVersion(String appVersion) {
		this.appVersion = appVersion;
	}

	@Column(name = "device_model_no", length = 100)
	public String getDeviceModelNo() {
		return this.deviceModelNo;
	}

	public void setDeviceModelNo(String deviceModelNo) {
		this.deviceModelNo = deviceModelNo;
	}

	@Column(name = "device_screen_size", precision = 8, scale = 0)
	public Double getDeviceScreenSize() {
		return this.deviceScreenSize;
	}

	public void setDeviceScreenSize(Double deviceScreenSize) {
		this.deviceScreenSize = deviceScreenSize;
	}

	@Column(name = "device_screen_resolution", length = 100)
	public String getDeviceScreenResolution() {
		return this.deviceScreenResolution;
	}

	public void setDeviceScreenResolution(String deviceScreenResolution) {
		this.deviceScreenResolution = deviceScreenResolution;
	}

}
