package com.ssinfo.ws.rider.mapping;

// Generated 4 Oct, 2014 9:40:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * LegsTbl generated by hbm2java
 */
@Entity
@Table(name = "legs_tbl", schema = "public")
public class LegsTbl implements java.io.Serializable {

	private long legsId;
	private LocationInfoTbl locationInfoTblByStartLocationId;
	private LocationInfoTbl locationInfoTblByEndLocationId;
	private RoutesTbl routesTbl;
	private Long distance;
	private Long duration;
	private String endAddress;
	private String startAddress;
	private Set<StepsTbl> stepsTbls = new HashSet<StepsTbl>(0);

	public LegsTbl() {
	}

	public LegsTbl(long legsId) {
		this.legsId = legsId;
	}

	public LegsTbl(long legsId,
			LocationInfoTbl locationInfoTblByStartLocationId,
			LocationInfoTbl locationInfoTblByEndLocationId,RoutesTbl routesTbl, Long distance,
			Long duration, String endAddress, String startAddress,
			Set<StepsTbl> stepsTbls) {
		this.legsId = legsId;
		this.routesTbl = routesTbl;
		this.locationInfoTblByStartLocationId = locationInfoTblByStartLocationId;
		this.locationInfoTblByEndLocationId = locationInfoTblByEndLocationId;
		this.distance = distance;
		this.duration = duration;
		this.endAddress = endAddress;
		this.startAddress = startAddress;
		this.stepsTbls = stepsTbls;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="search_sequence")
	@SequenceGenerator(
		name="search_sequence",sequenceName="search_sequence",	allocationSize=1)
	@Column(name = "legs_id", unique = true, nullable = false)
	public long getLegsId() {
		return this.legsId;
	}

	public void setLegsId(long legsId) {
		this.legsId = legsId;
	}
   
	@ManyToOne(fetch = FetchType.EAGER,cascade={CascadeType.REMOVE})
	@JoinColumn(name = "route_id")
	public RoutesTbl getRoutesTbl() {
		return this.routesTbl;
	}

	public void setRoutesTbl(RoutesTbl routesTbl) {
		this.routesTbl = routesTbl;
	}
	@ManyToOne(fetch = FetchType.EAGER,cascade={CascadeType.REMOVE})
	@JoinColumn(name = "start_location_id")
	public LocationInfoTbl getLocationInfoTblByStartLocationId() {
		return this.locationInfoTblByStartLocationId;
	}

	public void setLocationInfoTblByStartLocationId(
			LocationInfoTbl locationInfoTblByStartLocationId) {
		this.locationInfoTblByStartLocationId = locationInfoTblByStartLocationId;
	}

	@ManyToOne(fetch = FetchType.EAGER,cascade={CascadeType.REMOVE})
	@JoinColumn(name = "end_location_id")
	public LocationInfoTbl getLocationInfoTblByEndLocationId() {
		return this.locationInfoTblByEndLocationId;
	}

	public void setLocationInfoTblByEndLocationId(
			LocationInfoTbl locationInfoTblByEndLocationId) {
		this.locationInfoTblByEndLocationId = locationInfoTblByEndLocationId;
	}

	@Column(name = "distance")
	public Long getDistance() {
		return this.distance;
	}

	public void setDistance(Long distance) {
		this.distance = distance;
	}

	@Column(name = "duration")
	public Long getDuration() {
		return this.duration;
	}

	public void setDuration(Long duration) {
		this.duration = duration;
	}

	@Column(name = "end_address", length = 200)
	public String getEndAddress() {
		return this.endAddress;
	}

	public void setEndAddress(String endAddress) {
		this.endAddress = endAddress;
	}

	@Column(name = "start_address", length = 200)
	public String getStartAddress() {
		return this.startAddress;
	}

	public void setStartAddress(String startAddress) {
		this.startAddress = startAddress;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "legsTbl",cascade={CascadeType.REMOVE})
	public Set<StepsTbl> getStepsTbls() {
		return this.stepsTbls;
	}

	public void setStepsTbls(Set<StepsTbl> stepsTbls) {
		this.stepsTbls = stepsTbls;
	}

}
