package com.ssinfo.ws.rider.mapping;

// Generated 4 Oct, 2014 9:40:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;

/**
 * RoutesTbl generated by hbm2java
 */
@Entity
@Table(name = "routes_tbl", schema = "public")
public class RoutesTbl implements java.io.Serializable {

	private long routeId;
	private SearchInfoTbl searchInfoTbl;
	private Set<LegsTbl> legsTbls = new HashSet<LegsTbl>(0);
	private UserTbl userTbl;
	private String wayPoints;
	private String summary;

	public RoutesTbl() {
	}

	public RoutesTbl(long routeId) {
		this.routeId = routeId;
	}

	public RoutesTbl(long routeId, SearchInfoTbl searchInfoTbl,
			UserTbl userTbl, String wayPoints, String summary,Set<LegsTbl> legsTbls) {
		this.routeId = routeId;
		this.searchInfoTbl = searchInfoTbl;
		this.userTbl = userTbl;
		this.wayPoints = wayPoints;
		this.summary = summary;
		this.legsTbls = this.legsTbls;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="search_sequence")
	@SequenceGenerator(
		name="search_sequence",sequenceName="search_sequence",	allocationSize=1)
	@Column(name = "route_id", unique = true, nullable = false)
	public long getRouteId() {
		return this.routeId;
	}

	public void setRouteId(long routeId) {
		this.routeId = routeId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "search_id")
	public SearchInfoTbl getSearchInfoTbl() {
		return this.searchInfoTbl;
	}

	public void setSearchInfoTbl(SearchInfoTbl searchInfoTbl) {
		this.searchInfoTbl = searchInfoTbl;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "routesTbl",cascade={CascadeType.ALL})
		public Set<LegsTbl> getLegsTbls() {
		return this.legsTbls;
	}

	public void setLegsTbls(Set<LegsTbl> legsTbls) {
		this.legsTbls = legsTbls;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id")
	public UserTbl getUserTbl() {
		return this.userTbl;
	}

	public void setUserTbl(UserTbl userTbl) {
		this.userTbl = userTbl;
	}

	@Column(name = "way_points", length = 50)
	public String getWayPoints() {
		return this.wayPoints;
	}

	public void setWayPoints(String wayPoints) {
		this.wayPoints = wayPoints;
	}

	@Column(name = "summary", length = 200)
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

}
