package com.ssinfo.ws.rider.mapping;

// Generated 4 Oct, 2014 9:40:17 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * StepsTbl generated by hbm2java
 */
@Entity
@Table(name = "steps_tbl", schema = "public")
public class StepsTbl implements java.io.Serializable {

	private long stepsId;
	private LocationInfoTbl locationInfoTblByStartLocationId;
	private LegsTbl legsTbl;
	private LocationInfoTbl locationInfoTblByEndLocationId;
	private Long duration;
	private Long distance;

	public StepsTbl() {
	}

	public StepsTbl(long stepsId) {
		this.stepsId = stepsId;
	}

	public StepsTbl(long stepsId,
			LocationInfoTbl locationInfoTblByStartLocationId, LegsTbl legsTbl,
			LocationInfoTbl locationInfoTblByEndLocationId, Long duration,
			Long distance) {
		this.stepsId = stepsId;
		this.locationInfoTblByStartLocationId = locationInfoTblByStartLocationId;
		this.legsTbl = legsTbl;
		this.locationInfoTblByEndLocationId = locationInfoTblByEndLocationId;
		this.duration = duration;
		this.distance = distance;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="search_sequence")
	@SequenceGenerator(
		name="search_sequence",sequenceName="search_sequence",	allocationSize=1)
	@Column(name = "steps_id", unique = true, nullable = false)
	public long getStepsId() {
		return this.stepsId;
	}

	public void setStepsId(long stepsId) {
		this.stepsId = stepsId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "start_location_id")
	public LocationInfoTbl getLocationInfoTblByStartLocationId() {
		return this.locationInfoTblByStartLocationId;
	}

	public void setLocationInfoTblByStartLocationId(
			LocationInfoTbl locationInfoTblByStartLocationId) {
		this.locationInfoTblByStartLocationId = locationInfoTblByStartLocationId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "legs_id")
	public LegsTbl getLegsTbl() {
		return this.legsTbl;
	}

	public void setLegsTbl(LegsTbl legsTbl) {
		this.legsTbl = legsTbl;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "end_location_id")
	public LocationInfoTbl getLocationInfoTblByEndLocationId() {
		return this.locationInfoTblByEndLocationId;
	}

	public void setLocationInfoTblByEndLocationId(
			LocationInfoTbl locationInfoTblByEndLocationId) {
		this.locationInfoTblByEndLocationId = locationInfoTblByEndLocationId;
	}

	@Column(name = "duration")
	public Long getDuration() {
		return this.duration;
	}

	public void setDuration(Long duration) {
		this.duration = duration;
	}

	@Column(name = "distance")
	public Long getDistance() {
		return this.distance;
	}

	public void setDistance(Long distance) {
		this.distance = distance;
	}

}
