package com.ssinfo.ws.rider.mapping;

// Generated 4 Oct, 2014 9:40:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserTbl generated by hbm2java
 */
@Entity
@Table(name = "user_tbl", schema = "public")
public class UserTbl implements java.io.Serializable {

	private long userId;
	private String userName;
	private String status;
	private Date registrationDate;
	private Date registrationTime;
	private String emailId;
	private String gcmId;
	private Set<SearchInfoTbl> searchInfoTbls = new HashSet<SearchInfoTbl>(0);
	private Set<RoutesTbl> routesTbls = new HashSet<RoutesTbl>(0);
	private Set<DeviceInfoTbl> deviceInfoTbls = new HashSet<DeviceInfoTbl>(0);
	private Set<CoriderInfoTbl> coriderInfoTbls = new HashSet<CoriderInfoTbl>(0);

	public UserTbl() {
		
	}

	public UserTbl(long userId) {
		this.userId = userId;
	}

	public UserTbl(long userId, String userName, Date registrationDate,
			Date registrationTime, String emailId,
			Set<SearchInfoTbl> searchInfoTbls, Set<RoutesTbl> routesTbls,String gcmId,
			Set<DeviceInfoTbl> deviceInfoTbls,
			Set<CoriderInfoTbl> coriderInfoTbls,String status) {
		this.userId = userId;
		this.userName = userName;
		this.registrationDate = registrationDate;
		this.registrationTime = registrationTime;
		this.emailId = emailId;
		this.searchInfoTbls = searchInfoTbls;
		this.routesTbls = routesTbls;
		this.gcmId = gcmId;
		this.deviceInfoTbls = deviceInfoTbls;
		this.coriderInfoTbls = coriderInfoTbls;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="user_sequence")
	@SequenceGenerator(
		name="user_sequence",sequenceName="user_sequence",	allocationSize=1)
	@Column(name = "user_id", unique = true, nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}
	
	@Column(name = "gcm_id", unique = true, nullable = false)
	public String getGcmId() {
		return gcmId;
	}

	public void setGcmId(String gcmId) {
		this.gcmId = gcmId;
	}

	@Column(name = "user_name", length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "registration_date", length = 4)
	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "registration_time", length = 12)
	public Date getRegistrationTime() {
		return this.registrationTime;
	}

	public void setRegistrationTime(Date registrationTime) {
		this.registrationTime = registrationTime;
	}

	@Column(name = "email_id", length = 100)
	public String getEmailId() {
		return this.emailId;
	}
	
	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "userTbl",cascade={CascadeType.ALL})
	public Set<SearchInfoTbl> getSearchInfoTbls() {
		return this.searchInfoTbls;
	}

	public void setSearchInfoTbls(Set<SearchInfoTbl> searchInfoTbls) {
		this.searchInfoTbls = searchInfoTbls;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "userTbl",cascade={CascadeType.ALL})
	public Set<RoutesTbl> getRoutesTbls() {
		return this.routesTbls;
	}

	public void setRoutesTbls(Set<RoutesTbl> routesTbls) {
		this.routesTbls = routesTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTbl",cascade={CascadeType.ALL})
	public Set<DeviceInfoTbl> getDeviceInfoTbls() {
		return this.deviceInfoTbls;
	}

	public void setDeviceInfoTbls(Set<DeviceInfoTbl> deviceInfoTbls) {
		this.deviceInfoTbls = deviceInfoTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTbl")
	public Set<CoriderInfoTbl> getCoriderInfoTbls() {
		return this.coriderInfoTbls;
	}

	public void setCoriderInfoTbls(Set<CoriderInfoTbl> coriderInfoTbls) {
		this.coriderInfoTbls = coriderInfoTbls;
	}
	@Column(name = "status", length = 34)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
}
